### PR TITLE
Improve appearance of warning text; clean up styles

### PR DESCRIPTION
**Pull request by hacktivist123**
- [x] replace the small tag with div for styling to save CSS code because a small tag isn't supposed to be a block
- [x] increased the font-weight of the warning text
- [x] added padding to make it more visually appealing
- [x] Also a little bit of style clean up 😄

### CODE REVIEW

**Comment by shalvah** [comment]
Can I get a screenshot of what this looks like? You can copy the code and paste it into a random html file and open in your browser.

**Comment by hacktivist123** [comment]
Sent you a couple of messages on twitter with the screenshot :)

**Comment by hacktivist123** [comment]
imageimage

**Comment by shalvah** [comment]
Thanks. I'm not sure I want to draw that much attention to it, but we'll give it a try.

**Comment by hacktivist123** [comment]
Sure, just that I’ve noticed a lot of people complain that the bot hasn’t been replying them and that text isn’t obvious, so it would make sense to make it obvious to them to lessen the complaints.

**Pull request merged**
