### PR TITLE
Fix broken View tweet link

### PR DESCRIPTION
**Pull request by notpushkin**

### CODE REVIEW

**Comment by shalvah** [comment]
Errr...the current link seems to work fine.

**Comment by notpushkin** [comment]
Not for me:
image

Maybe you're still on the old design? They've broken a few links in the new one. The `/i/status/{tweet_id}` one should work on both (for now at least).

**Comment by shalvah** [comment]
Ah, I see. Just tried on a different PC and it doesn't work anymore. These folks keep breaking stuff.

**Comment by shalvah** [comment]
Thank you.

**Pull request merged**
